# Playbook to shutdown as series of WF servers via CLI command

- hosts: wildfly-servers

  tasks:
    - file: path=/tmp/{{wildfly}}    state=absent
    - file: path=/tmp/wf-installer.jar  state=absent
