# Playbook to shutdown as series of WF servers via CLI command

- hosts: wildfly-servers
  vars:
   #    wildfly: wildfly-9.0.1.Final
    wildfly: wildfly-10.0.0.CR2
    agent: hawkular-monitor-0.10.1.Final-SNAPSHOT-module.zip
    installer: agent-installer-0.10.1.Final-SNAPSHOT.jar

  tasks:
    - file: path=/tmp/{{wildfly}}    state=absent
    - file: path=/tmp/{{installer}}  state=absent
    - file: path=/tmp/{{agent}}      state=absent
