
- hosts: wildfly-servers

  roles: 
    # Fetch WildFly from jboss.org if needed
    - fetch_wildfly
    # Fetch agent from jboss.org if needed
    - fetch_agent
    - distribute-wildfly
    - distribute-agent
    - distribute-installer
    - configure-agent
    - start-wildfly

