# Playbook to shutdown as series of WF servers via CLI command

- hosts: wildfly-servers

  tasks:
    - command: "{{bin}}/jboss-cli.sh --connect --command=:shutdown"
      when: ansible_hostname != "snert"
    - command: "{{bin}}/jboss-cli.sh --connect controller=localhost:19990 --command=:shutdown"
      when: ansible_hostname == "snert"
